ALTER TABLE drivers
    MODIFY COLUMN verification_status
        ENUM('PENDING', 'REJECTED', 'VERIFIED', 'INCOMPLETE')
        NOT NULL DEFAULT 'INCOMPLETE';

ALTER TABLE vehicles
    MODIFY COLUMN fuel_type ENUM('PETROL', 'DIESEL', 'ELECTRIC', 'HYBRID') NOT NULL,
    MODIFY COLUMN transmission ENUM('MANUAL', 'AUTOMATIC') NOT NULL;

ALTER TABLE ride_requests
    MODIFY COLUMN ride_request_status ENUM('PENDING', 'ACCEPTED', 'CANCELLED', 'REJECTED') NOT NULL;

ALTER TABLE rides
    MODIFY COLUMN ride_status ENUM('SCHEDULED', 'ONGOING', 'COMPLETED', 'CANCELLED', 'REJECTED') NOT NULL;

ALTER TABLE vehicle_service
    MODIFY COLUMN vehicle_type ENUM('TWO_WHEELER', 'THREE_WHEELER', 'FOUR_WHEELER') NOT NULL;

ALTER TABLE rides
    MODIFY COLUMN payment_mode ENUM('CASH', 'CARD', 'UPI') NOT NULL;

ALTER TABLE rides
    MODIFY COLUMN payment_status ENUM('PENDING', 'PAID', 'FAILED') NOT NULL;

ALTER TABLE roles
    MODIFY COLUMN role_name ENUM('ROLE_SUPER_ADMIN', 'ROLE_CUSTOMER', 'ROLE_DRIVER') NOT NULL;